---
title: InforMARte es cuidarte (VERACRUZ)
author: Marea de DatODS
format: 
    dashboard:
        theme: [zephyr, custom.scss]
---

```{python}
# Importacion de librerias
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from ipyleaflet import Map, basemaps, Marker, basemap_to_tiles
```

```{python}
# Lectura de datos
nivel_del_mar = pd.read_csv("../datos/data-1_metros.csv")
temperatura = pd.read_csv("../datos/data-1_gradoscelsius.csv")
humedad_rel = pd.read_csv("../datos/data-1_porcentaje.csv")
velocidad_viento = pd.read_csv("../datos/data-1_metrosxsegundo.csv")
direccion_viento = pd.read_csv("../datos/data-1_grados.csv")
pronostico_meteorologia = pd.read_csv('../datos/meteorologia_veracruz_2026-04-20.csv')
poblacion_Veracruz = pd.read_csv('../datos/conjunto_de_datos_iter_30CSV20.csv', usecols=[3,5,9])
impacto_Nacional=pd.read_excel('../datos/Basehistorica_2000_a_2024.xlsx', usecols=[0,1,2,3,4,5,6,8,9,15])
```

```{python}
# Preparar los datos

#  1. Cambiar el nombre de las columnas en el dataframe 'nivel_del_mar'
nivel_del_mar.rename(columns={'Nivel del mar (radar promedio)':'Radar promedio', 'Nivel del mar (flotador)':'Flotador'},
                    inplace=True)

#  2. Creación de una nueva columna que contiene las fechas del archivo en formato 'datetime'
nivel_del_mar['Tiempo_datetime']=pd.to_datetime(nivel_del_mar['Tiempo'], format='%Y-%m-%d %H:%M:%S')
temperatura['Tiempo_datetime']=pd.to_datetime(temperatura['Tiempo'], format='%Y-%m-%d %H:%M:%S')
humedad_rel['Tiempo_datetime']=pd.to_datetime(humedad_rel['Tiempo'], format='%Y-%m-%d %H:%M:%S')
velocidad_viento['Tiempo_datetime']=pd.to_datetime(velocidad_viento['Tiempo'], format='%Y-%m-%d %H:%M:%S')
direccion_viento['Tiempo_datetime']=pd.to_datetime(direccion_viento['Tiempo'], format='%Y-%m-%d %H:%M:%S')
pronostico_meteorologia['Tiempo_datetime'] = pd.to_datetime(pronostico_meteorologia['date']+" "+pronostico_meteorologia['time'], 
                                                       format='%Y-%m-%d %H:%M:%S')

# 3.1 Transformación de hora UTC a hora local de los datos medidos
nivel_del_mar['Tiempo_local'] = nivel_del_mar['Tiempo_datetime'] - pd.to_timedelta(6,unit='h')
temperatura['Tiempo_local'] = temperatura['Tiempo_datetime'] - pd.to_timedelta(6,unit='h')
humedad_rel['Tiempo_local'] = humedad_rel['Tiempo_datetime'] - pd.to_timedelta(6,unit='h')
velocidad_viento['Tiempo_local'] = velocidad_viento['Tiempo_datetime'] - pd.to_timedelta(6,unit='h')
direccion_viento['Tiempo_local'] = direccion_viento['Tiempo_datetime'] - pd.to_timedelta(6,unit='h')


# 3.2 Se transforma la velocidad del viento del pronostico de km/h a m/s
pronostico_meteorologia['wind_speed_ms'] = (1000/3600) * pronostico_meteorologia['wind_speed_kmh']

#==============
# Semáforos de alerta
#==============
#temperatura
temp_actual = float(temperatura.iloc[-1]['Temperatura atmosferica'])
if temp_actual >=35:
    sem_temp = "Alerta por temperatura: 🔴"
elif temp_actual >=25:
    sem_temp = "Alerta por temperatura: 🟡"
else:
    sem_temp = "Alerta por temperatura: 🟢"

#nivel del mar
nivel_actual = float(nivel_del_mar['Radar promedio'].dropna().iloc[-1])
if nivel_actual > 2:
    sem_nivel_mar = "Alerta por nivel del mar: 🔴"
elif nivel_actual > 1:
    sem_nivel_mar= "Alerta por nivel del mar:🟡"
else:
    sem_nivel_mar = "Alerta por nivel del mar: 🟢"

#tsunami
estado_tsunami = "Sin alerta"
if estado_tsunami == "Alerta":
    sem_tsunami = "Alerta por tsunami: 🔴"
elif estado_tsunami == "Precaución":
    sem_tsunami = "Alerta por tsunami: 🟡"
else:
    sem_tsunami = "Alerta por tsunami: 🟢"
#huracán
estado_huracan = "Sin alerta"
if estado_huracan == "Alerta":
    sem_huracan = "Alerta por huracán: 🔴"
elif estado_huracan == "Precaución":
    sem_huracan = "Alerta por huracán: 🟡"
else:
    sem_huracan = "Alerta por huracán: 🟢"

#viento
viento_actual = float(velocidad_viento.iloc[-1]['Velocidad de rafaga'])
if viento_actual > 25:
    sem_viento = "Alerta por viento: 🔴"
elif viento_actual > 17:
    sem_viento = "Alerta por viento: 🟡"
else:
    sem_viento = "Alerta por viento: 🟢"

#lluvia
lluvia_actual = 10
if lluvia_actual > 30:
    sem_lluvia = "Alerta por lluvia: 🔴"
elif lluvia_actual > 20:
    sem_lluvia = "Alerta por lluvia: 🟡"
else:
    sem_lluvia = "Alerta por lluvia: 🟢"

#oleaje
oleaje_actual = 10
if oleaje_actual > 30:
    sem_oleaje = "Alerta por oleaje: 🔴"
elif oleaje_actual > 20:
    sem_oleaje = "Alerta por oleaje: 🟡"
else:
    sem_oleaje = "Alerta por oleaje: 🟢"

#marejada
marejada_actual = 10
if marejada_actual > 30:
    sem_marejada = "Alerta por marejada: 🔴"
elif marejada_actual > 20:
    sem_marejada = "Alerta por marejada: 🟡"
else:
    sem_marejada = "Alerta por marejada: 🟢"


#  4. Filtrado de datos de población de INEGI
poblacionXmunicipio = poblacion_Veracruz.loc[poblacion_Veracruz['NOM_LOC']=='Total del Municipio']
municipios_mas_poblados=poblacionXmunicipio.sort_values(by='POBTOT', ascending=False).iloc[0:10]

#  5. Filtrado de datos de impacto socioeconómico de CENAPRED
impacto_Veracruz=impacto_Nacional.loc[impacto_Nacional['Estado']=='Veracruz']
impacto_Veracruz_Hidrometeo=impacto_Veracruz.loc[impacto_Veracruz['Clasificación del fenómeno']=='Hidrometeorológico']

#   5.1. Clasificación de los fenómenos
num_tipo_fenomeno = impacto_Veracruz_Hidrometeo['Tipo de fenómeno'].value_counts().iloc[0:11]

#   5.2. Cuantificación de la población afectada
lluvias = impacto_Veracruz_Hidrometeo.loc[impacto_Veracruz_Hidrometeo['Tipo de fenómeno']=='Lluvias']
lluvias_poblacion_afect = lluvias['Población afectada '].replace('SD',0).sum()
poblacion_afect = {'Lluvias':lluvias_poblacion_afect}

inundacion = impacto_Veracruz_Hidrometeo.loc[impacto_Veracruz_Hidrometeo['Tipo de fenómeno']=='Inundación']
inundacion_poblacion_afect = inundacion['Población afectada '].replace('SD',0).sum()
poblacion_afect['Inundación']=inundacion_poblacion_afect

fuertes_vientos = impacto_Veracruz_Hidrometeo.loc[impacto_Veracruz_Hidrometeo['Tipo de fenómeno']=='Fuertes vientos ']
vientos_poblacion_afect = fuertes_vientos['Población afectada '].replace('SD',0).sum()
poblacion_afect['Fuertes vientos']=vientos_poblacion_afect

bajas_temperaturas = impacto_Veracruz_Hidrometeo.loc[impacto_Veracruz_Hidrometeo['Tipo de fenómeno']=='Bajas temperaturas ']
bajatemp_poblacion_afect = bajas_temperaturas['Población afectada '].replace('SD',0).sum()
poblacion_afect['Bajas temperaturas']=bajatemp_poblacion_afect

ciclon_tropical = impacto_Veracruz_Hidrometeo.loc[impacto_Veracruz_Hidrometeo['Tipo de fenómeno']=='Ciclón tropical']
ciclon_poblacion_afect = ciclon_tropical['Población afectada '].replace('SD',0).sum()
poblacion_afect['Ciclón tropical']=ciclon_poblacion_afect

#   5.3. Cuantificación de los daños en millones de pesos
lluvias_danos_econ = lluvias['Total de daños (millones de pesos)'].sum()
danos_economicos = {'Lluvias':lluvias_danos_econ}

inundacion_danos_econ = inundacion['Total de daños (millones de pesos)'].sum()
danos_economicos['Inundación']=inundacion_danos_econ

ciclon_danos_econ = ciclon_tropical['Total de daños (millones de pesos)'].sum()
danos_economicos['Ciclón tropical']=ciclon_danos_econ

#   5.4. Impacto socioeconómico
impacto_social = pd.Series(poblacion_afect).sort_values(ascending=False)
impacto_economico = pd.Series(danos_economicos).sort_values(ascending=False)
```

# Sabías que...

## Column {height=13%}
::: {.valuebox icon="exclamation-triangle-fill" color="primary"}
De 2000 a 2024 el estado de Veracruz fue impactado más de 300 veces por fenómenos meteorológicos y del mar, lo que equivale a al menos ¡10 desastres por año!
:::

::: {.valuebox icon="tropical-storm" color="primary"}
Según el Atlas de Riesgos del estado de Veracruz, ¡la entidad ocupa el segundo lugar a nivel nacional en impactos por ciclones tropicales!
:::

## Column {height=3%}
::: {.card title="Conoce los fenómenos meteorológicos y del mar que afectaron a Veracruz durante 2000 - 2024"}
```{python}
#| output: False
fig1=px.bar(num_tipo_fenomeno, color_discrete_sequence=['rgb(26, 118, 255)'], text_auto=True)
```
```{python}
fig1.update_layout(xaxis_title=" ", yaxis_title="Número de eventos", showlegend=False)
```
Fuente de los datos: [Atlas Nacional de Riesgos](http://www.atlasnacionalderiesgos.gob.mx/archivo/descargas.html){target="_blank"}
:::

## Column {height=3%}
::: {.card title="Conoce el impacto de fenómenos meteorológicos y del mar durante 2000 - 2024"}
```{python}
#| output: False
#| layout-ncol: 2
fig2=px.bar(impacto_social, color_discrete_sequence=['rgb(26, 118, 255)'], text_auto=True)
fig3=px.bar(impacto_economico, color_discrete_sequence=['rgb(26, 118, 255)'], text_auto=True)
```
```{python}
#| layout-ncol: 2
fig2.update_layout(xaxis_title=" ", yaxis_title="Población afectada", showlegend=False)
fig3.update_layout(xaxis_title=" ", yaxis_title="Daños en millones de pesos", showlegend=False)
```
Fuente de los datos: [Atlas Nacional de Riesgos](http://www.atlasnacionalderiesgos.gob.mx/archivo/descargas.html){target="_blank"}
:::


## Column {height=10%}
::: {.valuebox icon="people-fill" color="primary"}
De acuerdo con INEGI, en el municipio de Veracruz viven más de 600,000 personas, es decir, ¡más de medio millón de personas expuestas a impactos por fenómenos meteorológicos y del mar!
:::

## Column {height=3%}
::: {.card title="Conoce los municipios más poblados del estado de Veracruz"}
```{python}
#| output: False
fig=px.bar(municipios_mas_poblados, x='NOM_MUN', y='POBTOT', color_discrete_sequence=['indianred'], text_auto=True)
```
```{python}
fig.update_layout(xaxis_title=" ", yaxis_title="Población total", xaxis_tickangle=45)
```
Fuente de los datos: [Instituto Nacional de Estadística y Geografía (INEGI)](https://www.inegi.org.mx/programas/ccpv/2020/#datos\_abiertos){target="_blank"}
:::


# Pronósticos y condiciones actuales
## Row {height=20%}
### Column
```` {python}
#| component: valuebox
#| title: "Temperatura [°C]"
dict(
    icon="thermometer-half", 
    color="primary",
    value=float(temperatura.iloc[-1]['Temperatura atmosferica'])
)
````

### Column 
```{python}
#| component: valuebox
#| title: Lluvia [mm]
dict(
    icon="cloud-rain", 
    color="primary", 
    value=round(float(pronostico_meteorologia['hourly_precip_mm'][62]), 2)
)
```
### Column
```{python}
#| component: valuebox
#| title: Viento [m/s]
dict(
    icon="wind", 
    color="primary", 
    value=float(velocidad_viento.iloc[-1]['Velocidad de rafaga'])
)
```
### Column
```{python}
#| component: valuebox
#| title: Dirección viento [°]
dict(
    icon="compass", 
    color="primary", 
    value=round(float(direccion_viento.iloc[-1]['Direccion de rafaga']),1)
)
```

## Row {height=2%}

::: {.card title="Conoce más"}
[¡Conoce los riesgos por altas temperaturas!](https://www.imss.gob.mx/sites/all/statics/pdf/guarderias/onda-calor.pdf){target="_blank"}
```{python}
#| output: False
fig=go.Figure()
fig.add_trace(go.Scatter(x=temperatura['Tiempo_local'], y=temperatura['Temperatura atmosferica'], name='Medición', line=dict(color='green',width=3)))
fig.add_trace(go.Scatter(x=pronostico_meteorologia['Tiempo_datetime'], y=pronostico_meteorologia['temperature_C'], 
                name='Pronóstico', line=dict(color='blue',width=3)))
```
```{python}
fig.update_layout(xaxis_title=" ", yaxis_title="[°C]")
```
Fuente de los datos: [Servicio Mareográfico Nacional](https://www.mareografico.unam.mx/estaciones/?estacion=1){target="_blank"} (datos medidos), [Instituto de Ciencias de la Atmósfera y Cambio Climático](https://pronosticos.atmosfera.unam.mx/){target="_blank"} (datos pronóstico)
:::

### Column
::: {.card title="Conoce más"}
[¿Qué tan fuerte va a llover?](https://x.com/conagua_clima/status/1017166937569161217){target="_blank"}
```{python}
#| output: False
fig=go.Figure()
fig.add_trace(go.Scatter(x=pronostico_meteorologia['Tiempo_datetime'], y=pronostico_meteorologia['hourly_precip_mm'], 
                name='Medición', line=dict(color='blue',width=3)))
```
```{python}
fig.update_layout(xaxis_title=" ", yaxis_title="[mm]")
```
Fuente de los datos: [Instituto de Ciencias de la Atmósfera y Cambio Climático](https://pronosticos.atmosfera.unam.mx/){target="_blank"}

:::

### Column
::: {.card title="Conoce más"}
[¿Qué hago si hay vientos fuertes?](https://www.facebook.com/photo/?fbid=1299650188878277&set=a.466284112214893){target="_blank"}
```{python}
#| output: False
fig=go.Figure()
fig.add_trace(go.Scatter(x=velocidad_viento['Tiempo_local'], y=velocidad_viento['Rapidez de viento'], name='Medición', line=dict(color='green',width=3)))
fig.add_trace(go.Scatter(x=pronostico_meteorologia['Tiempo_datetime'], y=pronostico_meteorologia['wind_speed_ms'], 
                name='Pronóstico', line=dict(color='blue',width=3)))
```
```{python}
fig.update_layout(xaxis_title=" ", yaxis_title="[m/s]")
```
Fuente de los datos: [Servicio Mareográfico Nacional](https://www.mareografico.unam.mx/estaciones/?estacion=1){target="_blank"} (datos medidos), [Instituto de Ciencias de la Atmósfera y Cambio Climático](https://pronosticos.atmosfera.unam.mx/){target="_blank"} (datos pronóstico)
:::

### Column
::: {.card title="Conoce más"}
```{python}
#| output: False
fig=go.Figure()
fig.add_trace(go.Scatter(x=direccion_viento['Tiempo_local'], y=direccion_viento['Direccion de rafaga'], name='Medición', line=dict(color='green',width=3)))
fig.add_trace(go.Scatter(x=pronostico_meteorologia['Tiempo_datetime'], y=pronostico_meteorologia['wind_direction_deg'], 
                name='Pronóstico', line=dict(color='blue',width=3)))
```
```{python}
fig.update_layout(xaxis_title=" ", yaxis_title="[°]")
```
Fuente de los datos: [Servicio Mareográfico Nacional](https://www.mareografico.unam.mx/estaciones/?estacion=1){target="_blank"} (datos medidos), [Instituto de Ciencias de la Atmósfera y Cambio Climático](https://pronosticos.atmosfera.unam.mx/){target="_blank"} (datos pronóstico)
:::

## Row {height=5%}

::: {.card expandable="false"}
```{python}
#| echo: false
print(sem_temp)
```
:::


::: {.card expandable="false"}
```{python}
#| echo: false
print(sem_lluvia)
```
:::

### Column
::: {.card expandable="false"}
```{python}
#| echo: false
print(sem_viento)
```
:::


## Row {height=20%}
### Column 
```{python}
#| component: valuebox
#| title: Nivel mar [metros]
dict(
    icon="water", 
    color="primary", 
    value=round(float(nivel_del_mar['Radar promedio'].dropna().iloc[-1]),1)
)
```
### Column 
```{python}
#| component: valuebox
#| title: Oleaje [metros]
dict(
    icon="tsunami", 
    color="primary", 
    value="---"
)
```
### Column
```{python}
#| component: valuebox
#| title: Marejada [metros]
dict(
    icon="exclamation-diamond-fill", 
    color="primary", 
    value="---"
)
```
### Column
```{python}
#| component: valuebox
#| title: Humedad [%]
dict(
    icon="droplet-half", 
    color="primary", 
    value=f"{float(humedad_rel.iloc[-1]['Humedad relativa']):.1f}%"
)
```

## Row {height=2%}

::: {.card title="Conoce más"}
```{python}
#| output: False
fig=go.Figure()
fig.add_trace(go.Scatter(x=nivel_del_mar['Tiempo_local'], y=nivel_del_mar['Radar promedio'], name='Medición', line=dict(color='green',width=3)))
fig.add_trace(go.Scatter(x=nivel_del_mar['Tiempo_local'], y=nivel_del_mar['Pronostico'], 
                name='Pronóstico', line=dict(color='blue',width=3)))
```
```{python}
fig.update_layout(xaxis_title=" ", yaxis_title="[m]")
```
Fuente de los datos: [Servicio Mareográfico Nacional](https://www.mareografico.unam.mx/estaciones/?estacion=1){target="_blank"}
:::

### Column
::: {.card title="Conoce más"}
[¡Cuidado con el oleaje alto!](https://www.facebook.com/photo/?fbid=1156721736491620&set=pcb.1156721779824949){target="_blank"}
```{python}
fig=go.Figure()
fig.add_trace(go.Scatter(x=nivel_del_mar['Tiempo_datetime'], y=nivel_del_mar['Radar promedio'], name='Medición', line=dict(color='green',width=2)))
```
:::

### Column
::: {.card title="Conoce más"}
[¿Qué hago si hay marejadas?](https://www.facebook.com/photo/?fbid=1380740490766282&set=a.360223536151321){target="_blank"}
```{python}
figH=go.Figure()
figH.add_trace(go.Scatter(x=humedad_rel['Tiempo_datetime'], y=humedad_rel['Humedad relativa'], name='Medición', line=dict(color='green',width=2)))
```
:::

### Column
::: {.card title="Conoce más"}
```{python}
#| output: False
fig=go.Figure()
fig.add_trace(go.Scatter(x=humedad_rel['Tiempo_local'], y=humedad_rel['Humedad relativa'], name='Medición', line=dict(color='green',width=3)))
fig.add_trace(go.Scatter(x=pronostico_meteorologia['Tiempo_datetime'], y=pronostico_meteorologia['relative_humidity_pct'], 
                name='Pronóstico', line=dict(color='blue',width=3)))
```
```{python}
fig.update_layout(xaxis_title=" ", yaxis_title="[%]")
```
Fuente de los datos: [Servicio Mareográfico Nacional](https://www.mareografico.unam.mx/estaciones/?estacion=1){target="_blank"} (datos medidos), [Instituto de Ciencias de la Atmósfera y Cambio Climático](https://pronosticos.atmosfera.unam.mx/){target="_blank"} (datos pronóstico)
:::


## Row {height=5%}
### Column
::: {.card expandable="false"}
```{python}
#| echo: false
print(sem_nivel_mar)
```
:::
### Column
::: {.card expandable="false"}
```{python}
#| echo: false
print(sem_oleaje)
```
:::
### Column
::: {.card expandable="false"}
```{python}
#| echo: false
print(sem_marejada)
```
:::


## Row {height=20%}
### Column
::: {.valuebox icon="tsunami" color="light"}
[Consulta el último boletín del Centro de Alerta de Tsunamis](https://diredimoat.semar.gob.mx/cat/centroAlertasTsunamis.html){target="_blank"}
```{python}
#| echo: false
print(sem_tsunami)
```
:::

### Column
#### Row
:::{.card expandable="False"}
[¿Qué hago en caso de tsunami?](https://diredimoat.semar.gob.mx/cat/Archivos/Medidas.pdf){target="_blank"}
:::

#### Row
:::{.card expandable="False"}
[¿Qué hago en caso de huracán?](https://www.gob.mx/cms/uploads/attachment/file/926668/Infografi_as_-_Huracanes.pdf){target="_blank"}
:::

### Column
::: {.valuebox icon="hurricane" color="light"}
[Consulta el pronóstico del Servicio Meteorológico](https://smn.conagua.gob.mx/es/pronosticos/pronosticossubmenu/pronostico-meteorologico-general){target="_blank"}
```{python}
#| echo: false
print(sem_huracan)
```
:::

